---
apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sources:
    - alias: monorepo
      kind: GitRepository
      name: flux-system
  artifacts:
    - name: infrastructure
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/infrastructure/**"
          to: "@artifact/"
    - name: apps
      originRevision: "@monorepo"
      copy:
        - from: "@monorepo/apps/base/**"
          to: "@artifact/base/"
        - from: "@monorepo/apps/staging/**"
          to: "@artifact/staging/"
